language: java
env:
  global:
    secure: 
      - "PD4pOggC8HhrFMJBu1QF9cOO0hDu6REYb5jc67Rxw/8yOlmdQTNnyt6hgCY0a+3bkqPJh18RvmGG+bcZCEryTVWrWoonV9YvxyJq1v5BtA56GrbIVVFs+GtVynbilN8radiHuTSkXkqWhYtZqRpjyUhNOtorplthLCFqvuxUgNlrX5A7v4paNX64DY6O63KbaZ7DJ6DCMj0En90attUJ1PVeKNxqP37TObPAsz+0mDo214GUyGRyJ6D2LPNBnzVb1GsUouJgSbB7yY5Iv34XcKyqUn37NX9FfgKgnOP50SIEogGpwZ6V6LzUJiXKgG0gfD2ye4t0GM5viE/lN6g8yoVMZQRt4q0iVN5GTebFDjTMh7bUdF71zBGkWDH305x4i61nkJgAvVbcVyzwHPtim2VHGXKQOOIOL6EzsOFEzTTiqu2LXwV25z+N/urqYQbo31wabT6hq5f/k73iNuFOy5DqkHThjiE+EQmHAKf4wFGCvxSsxicLIeH4ODzgbEMhXF6LLKS45U82eozDN5vNKY+9FvrbEOEDIxUCup+pCU2rjYMS1TExVddYLETaqrWnHfp9KlgO5BetvKWI0lcMQxIyJZ0fF2bt8vRT/MBaZFoSwSuRXbMbKlkCdXKv23FlzXrkQVQcXcvEetDBCBMI+F4swHUIF8Y+reWK+tfpXF4="
      - "CB4FvO7S8mwpeAtWcKXrddb/jHz+t2QKdXo7fRe+/GgxGVTAGpwsDiBWuTp73YnVjaq0ynnkYLDREdCV3+VmR4z8WoJ/uWcCc/Rl1jJTDvgznL702U9nRJm8djSqUssTLu58YE3ETen4J59I0thH9kIRYgzWElbFP1BRccuPg80Qvh5B0EsmuaSGLrz1tZjYn2P/E5TSj5qzw803fIbgxudvwBJHH/301I0GA269HUjYi7mpbnvv32gj4ahyXWre3IBwFcYZV+KRG6bkkJhO/E008Jog77O9XGY9v/+Vkf/ImC42Mg6dL1u/TIfDHOilFJHU9/Naa8NXzGl/x2dEbcNA2o3FY/KkfnxTS6Wu3iBNg7/Zv3GTc589MgLp08QinG9UlbVIPwkjOwOUKddM64tg0sarpze//6lTLFePQh1nWnyLelZZHcHpM1Nu6VXZ+1nXzScTGmwlvMUfh2r1kf6VgT3XXgrhaDq5xXTxNM+7QmAdFtvOSngbxts1AOMibwMprm9KcXL0Uv9Lvy53GnpmW7ZVmAvHxdTRXHXfZK+JL2US+/P+eiPcQ5Px9qBGx9RJRQNAWOpO/IbbhA8xuRk+AAR7ULfgdU+07NAgRHHjj20RSqDWisG0Vm275OTj7e8Yl4fLF2j27B1UvBgacMiBFaHINpBaqFIh1UxmYYk="
services:
  - docker

script:
- docker build -t android-cordova:0.0.1 .
- docker tag android-cordova:0.0.1 grouepsii/android-cordova:0.0.1
- echo "$DOCKER_HUB_PASS" | docker login -u $DOCKER_HUB_LOGIN --password-stdin
- docker push groupesii/android-cordova:0.0.1
